name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm test
      - run: npm run build

      - name: SonarCloud Code Analysis
        uses: sonarsource/sonarcloud-github-action@v1.5
        with:
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          organization: "<your-sonarcloud-org>"
          token: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ecom-api-gateway:${{ github.sha }} .

      - name: Push Docker Image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | gcloud auth activate-service-account --key-file=-
          gcloud auth configure-docker
          docker push gcr.io/$PROJECT_ID/ecom-api-gateway:${{ github.sha }}

